---
deployment:
  tasks:
    # 1. Cria a pasta destino caso não exista
    - /bin/mkdir -p $HOME/public_html/sm-claude

    # 2. Copia o conteúdo de 'public/' (incluindo arquivos ocultos) para a pasta pública
    - /bin/cp -R public/. $HOME/public_html/sm-claude/

    # 3. Ajusta permissões
    - /bin/find $HOME/public_html/sm-claude -type d -exec chmod 755 {} \;
    - /bin/find $HOME/public_html/sm-claude -type f -exec chmod 644 {} \;
